spring:
  config:
    activate:
      on-profile: preproduccion
  datasource:
    url: jdbc:postgresql:///postgres?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    function:
      definition: orderCreatedConsumer
    gcp:
      # Eliminamos project-id fijo para que use el del entorno de Cloud Run
      sql:
        enabled: false
      pubsub:
        enabled: true
    stream:
      defaultBinder: pubsub
      bindings:
        order-created-out-0:
          destination: order-created
          content-type: application/json
        orderCreatedConsumer-in-0:
          destination: order-created
          group: notification-service
          content-type: application/json
      pubsub:
        default:
          consumer:
            auto-create-resources: false
          producer:
            auto-create-resources: false
        bindings:
          orderCreatedConsumer-in-0:
            consumer:
              auto-create-resources: false
          order-created-out-0:
            producer:
              auto-create-resources: false
  
gohost:
  fcm:
    enabled: true
    project-id: project-1f43bc6d-114e-44c8-bf4 # Unified Firebase project ID

logging:
  level:
    com.zms.gohostdeliveryservice: INFO
    org.springframework.cloud.stream: INFO
    org.springframework.kafka: WARN
