spring:
  application:
    name: gohostdelivery-service
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: gohostdelivery-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

kafka:
  topics:
    order-created: order-created

server:
  port: 8080

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yml
