<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.zms.gohostdeliveryservice</groupId>
    <artifactId>gohostdelivery-service-app</artifactId>
    <version>1.0.0</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>gohostdelivery-service-app-domain</artifactId>
  <name>${project.groupId}:${project.artifactId}</name>
  <description>Domain module - entities, ports and domain exceptions</description>

  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
  </dependencies>
</project>
